config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :schedules
  resources :rooms
  devise_for :users
  root 'schedules#index'
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match "/indexteacher/:id" =>"users#indexteacher", :as => :teacher, via: :get
  match "/indexuser/:id" =>"users#indexuser", :as => :student, via: :get

end

app/models/user.rb
class User < ApplicationRecord

  enum role: [:user, :teacher, :admin]
  after_initialize :set_default_role, if: :new_record?
  after_initialize :set_default_course, if: :new_record?
  belongs_to :course

  def set_default_role
    self.role ||= :user
  end

  def set_default_course
    self.course_id = 0
  end

  has_many :schedules
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized
  def index
    @users = User.all
    @courses = Course.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => 'User delected'
  end

  def update
    @user = User.find(params[:id])
    authorize @user

    if @user.update_attributes(secure_params)
      redirect_to users_path, :success => 'User updated'
    else
      redirect_to users_path, :alert => 'Unable to update user'
    end
  end

  def indexteacher
    user = User.find(params[:id])
    authorize user
    @schedules = Schedule.where("user_id = ?", user.id).all
  end

  def indexuser
    user = User.find(params[:id])
    authorize user
    @schedules = Schedule.where("course_id = ?", user.course_id).all
  end

  private

  def secure_params
    params.require(:user).permit(:role, :course_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>

<td>
  <%= simple_form_for(user) do |f| %>
    <% if user.role != "user" %>
      <%= f.select :role, User.roles.keys.map {|role| [role.titleize,role]}, {}, { class: 'form-control' } %>
      <td>
        <%= f.submit 'Change Role', class: 'btn btn-primary' %>
      </td>
    <% else %>
      <%= f.input :course_id, collection: @courses, label: false, value_method: :id, include_blank: false, selected: user.course_id %>
      <td>
        <%= f.submit 'Change Class', class: 'btn btn-primary' %>
      </td>
    <% end %>
  <% end %>
</td>

<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button') unless user == current_user %>
</td>

app/views/users/index.html.erb
<% admin = @users.select { |w| w.role == "admin" }%>
<% teacher = @users.select { |w| w.role == "teacher" }%>
<% student = @users.select { |w| w.role == "user" && w.course_id != 1}%>
<% none = @users.select { |w| w.role == "user" && w.course_id == 1}%>

<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title" style="text-align: left;">Manage User</h3>
                    <span class="pull-right">
                        <!-- Tabs -->
                        <ul class="nav panel-tabs">
                            <li class="active"><a href="#tab1" data-toggle="tab">Admin</a></li>
                            <li><a href="#tab2" data-toggle="tab">Teacher</a></li>
                            <li><a href="#tab3" data-toggle="tab">Student</a></li>
                            <li><a href="#tab4" data-toggle="tab">None</a></li>
                        </ul>
                    </span>
                </div>
                <div class="panel-body">
                    <div class="tab-content">
                        <div class="tab-pane active" id="tab1">
                            <table class="table table-hover">
                                <tbody>
                                    <% admin.each do |user| %>
                                        <tr>
                                            <%= render user %>
                                        </tr>
                                    <% end %>
                                </tbody>
                            </table>
                        </div>
                        <div class="tab-pane" id="tab2">
                            <table class="table table-hover">
                                <tbody>
                                    <% teacher.each do |user| %>
                                        <tr>
                                            <%= render user %>
                                        </tr>
                                    <% end %>
                                </tbody>
                            </table>
                        </div>
                        <div class="tab-pane" id="tab3">
                            <table class="table table-hover">
                                <tbody>
                                    <% student.each do |user| %>
                                        <tr>
                                            <%= render user %>
                                        </tr>
                                    <% end %>
                                </tbody>
                            </table>
                        </div>
                        <div class="tab-pane" id="tab4">
                            <table class="table table-hover">
                                <tbody>
                                    <% none.each do |user| %>
                                        <tr>
                                            <%= render user %>
                                        </tr>
                                    <% end %>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
  </div>
</div>

app/views/users/indexteacher.html.erb
<h1>Schedules</h1>
<div class="container">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>STT</th>
        <th>Subject</th>
        <th>Period start</th>
        <th>Period end</th>
        <th>Day of week</th>
        <th>Week start</th>
        <th>Week end</th>
        <th>Year</th>
        <th>Room</th>
        <th>Class</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% i=0 %>
      <% @schedules.each do |schedule| %>
      <% days = [ 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] %>
        <tr>
          <td><%= i=i+1 %></td>
          <td><%= schedule.subject %></td>
          <td><%= schedule.period_start %></td>
          <td><%= schedule.period_end %></td>
          <td><%= days[schedule.day_of_week.to_i] %></td>
          <td><%= schedule.week_start %></td>
          <td><%= schedule.week_end %></td>
          <td><%= schedule.year %></td>
          <td><%= schedule.room.name %></td>
          <td><%= schedule.course.name %></td>
          <td>
            <%= link_to 'Edit', edit_schedule_path(schedule) %>/
            <%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>

app/views/users/indexuser.html.erb
<h1>Schedules</h1>
<div class="container">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>STT</th>
        <th>Subject</th>
        <th>Period start</th>
        <th>Period end</th>
        <th>Day of week</th>
        <th>Week start</th>
        <th>Week end</th>
        <th>Year</th>
        <th>Room</th>
      </tr>
    </thead>

    <tbody>
      <% i = 0 %>
      <% @schedules.each do |schedule| %>
      <% days = [ 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] %>
        <tr>
          <td><%= i = i+1 %></td>
          <td><%= schedule.subject %></td>
          <td><%= schedule.period_start %></td>
          <td><%= schedule.period_end %></td>
          <td><%= days[schedule.day_of_week.to_i] %></td>
          <td><%= schedule.week_start %></td>
          <td><%= schedule.week_end %></td>
          <td><%= schedule.year %></td>
          <td><%= schedule.room.name %></td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>