config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :schedules
  resources :rooms
  devise_for :users
  root 'schedules#index'
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match "/indexteacher/:id" =>"users#indexteacher", :as => :teacher, via: :get
  match "/indexuser/:id" =>"users#indexuser", :as => :student, via: :get

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :room
  belongs_to :user
  belongs_to :course

    def self.dup_time?(schedule)
    temp = Schedule.where(room_id: schedule.room_id, day_of_week: schedule.day_of_week, year: schedule.year)
    temp.each do |t|
      next if t.id == schedule.id
      if (check_condition1(t.period_start, schedule.period_start, t.period_end) || check_condition1(t.period_start, schedule.period_end, t.period_end) || check_condition2(t.period_start, schedule.period_start, schedule.period_end, t.period_end)) && (check_condition1(t.week_start, schedule.week_start, t.week_end) || check_condition1(t.week_start, schedule.week_end, t.week_end) || check_condition2(t.week_start, schedule.week_start, schedule.week_end, t.week_end))
        binding.pry
        return true
      end
    end
    return false
  end

  def self.dup_class?(schedule)
    temp = Schedule.where(course_id: schedule.course_id, day_of_week: schedule.day_of_week, year: schedule.year)
    temp.each do |t|
      next if t.id == schedule.id
      if (check_condition1(t.period_start, schedule.period_start, t.period_end) || check_condition1(t.period_start, schedule.period_end, t.period_end) || check_condition2(t.period_start, schedule.period_start, schedule.period_end, t.period_end)) && (check_condition1(t.week_start, schedule.week_start, t.week_end) || check_condition1(t.week_start, schedule.week_end, t.week_end) || check_condition2(t.week_start, schedule.week_start, schedule.week_end, t.week_end))
        binding.pry
        return true
      end
    end
    return false
  end

  def self.check_condition1(start, value, _end)
    if start <= value && value <= _end
      return true
    else
      return false
    end
  end

  def self.check_condition2(start, value_start, value_end, _end)
    if start > value_start && value_end > _end
      return true
    else
      return false
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :get_rooms_and_course, only: [:new, :edit, :index]
  # GET /schedules
  # GET /schedules.json
  def index
    if params[:search].nil?
      @date = Time.now
      @week = Time.now.strftime("%W")
      @day_of_week = Time.now.strftime("%u").to_i - 1
      @year = Time.now.strftime("%Y")
    else
      @date = params[:search].to_time
      @week = @date.strftime("%W")
      @day_of_week = @date.strftime("%u").to_i - 1
      @year = @date.strftime("%Y")
    end
    @schedules = Schedule.where(
      "day_of_week = ? AND week_start <= ? AND week_end >= ? AND year = ?",
      @day_of_week, @week, @week, @year).all
    # @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = current_user.schedules.build
  end

  # GET /schedules/1/edit
  def edit
    authorize @schedule
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = current_user.schedules.build(schedule_params)
    authorize @schedule
    if Schedule.dup_time?(@schedule) || Schedule.dup_class?(@schedule)
      redirect_back(fallback_location: session[:previous], alert: 'Conflict Time!')
    elsif @schedule.save
      redirect_to @schedule, notice: 'Schedule was successfully created.'
    else
      render 'new'
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    temp = current_user.schedules.build(schedule_params)
    temp.id = params[:id]
    authorize @schedule
    if Schedule.dup_time?(temp) || Schedule.dup_class?(temp)
      binding.pry
      redirect_back(fallback_location: session[:previous], alert: 'Conflict Time!')
    elsif @schedule.update(schedule_params)
      redirect_to @schedule, notice: 'Schedule was successfully updated.'
    else
      render 'new'
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    authorize @schedule
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:subject, :description, :period_start, :period_end, :day_of_week, :week_start, :week_end, :year, :room_id, :course_id)
    end

    def get_rooms_and_course
      @rooms = Room.all
      @courses = Course.order(id: :asc).offset(1)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.haml
= simple_form_for @schedule do |f|
  .form-group
    = f.input :subject
  .form-group
    = f.input :description
  .form-group.col-md-6
    = f.input :period_start, collection: 1..9, selected: @schedule.period_start, :input_html => {:onchange => "change_period()"}
  .form-group.col-md-6
    = f.input :period_end, collection: 2..10, selected: @schedule.period_end
  .form-group
    = f.input :day_of_week, collection: Date::DAYS_INTO_WEEK
  .form-group
    .col-md-6
      = f.input :week_start
    .col-md-6
      = f.input :week_end
  .form-group
    = f.input :year, collection: [Time.now.year,Time.now.year+1], selected: Time.now.year
  .form-group
    = f.input :room_id, collection: @rooms, label_method: :name, value_method: :id,label: "Location", include_blank: false, selected: @schedule.room_id
  .form-group
    = f.input :course_id, collection: @courses, label_method: :name, value_method: :id,label: "Class", include_blank: false, selected: @schedule.course_id

  = f.button :submit, class: "btn btn-info"

app/views/schedules/edit.html.haml
.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Post Schedule
      .panel-body
        = render 'form'

app/views/schedules/index.html.erb
<h1>Schedules</h1>
<h3><%= @date.strftime("%d/%m/%Y") %></h3>
<h3>Week: <%= @week %></h3>

<script>
  $( function() {
    $( "#search" ).datepicker({ dateFormat: 'dd-mm-yy' });
  });
</script>

<div class="container">
  <div class="row">
    <div class="col-lg-3">
            <form class="input-group custom-search-form" action="/" onSubmit="return saveComment();">
              <input type="text" class="form-control" id="search" name="search">
              <span class="input-group-btn">
              <button class="btn btn-primary" type="submit">
              <span class="glyphicon glyphicon-search"></span>
             </button>
             </span>
             </form><!-- /input-group -->
    </div>
  </div>
</div>

<div class="container">
  <div class="table-responsive">
    <table class="table table-hover" id="schedule">
      <thead>
        <th>Room</th>
        <% 10.times do |n| %>
        <th><%= n+1 %></th>
        <% end %>
      </thead>

      <tbody>
        <% @rooms.each do |room|%>
          <% schedule = @schedules.select { |w| w.room_id == room.id }%>
          <tr>
            <td class="row_schedule"><%= room.name %></td>
              <% 10.times do |n|%>
                <% flag = false %>
                <% schedule.each do |s|%>
                  <% if (n+1) >= s.period_start && (n+1) <= s.period_end %>
                    <td class="row_schedule"><%= link_to s.course.name, schedule_path(s.id) %></td>
                    <% flag = true %>
                    <% break %>
                  <% end %>
                <% end %>
                <% if flag == true %>
                  <% next %>
                <% else %>
                  <td class="row_schedule"></td>
                <% end %>
              <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>

  <%= link_to 'New Schedule', new_schedule_path %>
</div>

app/views/schedules/new.html.haml
.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Post Schedule
      .panel-body
        = render 'form'

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @schedule.subject %>
</p>

<p>
  <strong>Description:</strong>
  <%= @schedule.description %>
</p>

<p>
  <strong>Period start:</strong>
  <%= @schedule.period_start %>
</p>

<p>
  <strong>Period end:</strong>
  <%= @schedule.period_end %>
</p>

<p>
  <strong>Day of week:</strong>
  <%= @schedule.day_of_week %>
</p>

<p>
  <strong>Week start:</strong>
  <%= @schedule.week_start %>
</p>

<p>
  <strong>Week end:</strong>
  <%= @schedule.week_end %>
</p>

<p>
  <strong>Year:</strong>
  <%= @schedule.year %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>