config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :schedules
  resources :rooms
  devise_for :users
  root 'schedules#index'
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match "/indexteacher/:id" =>"users#indexteacher", :as => :teacher, via: :get
  match "/indexuser/:id" =>"users#indexuser", :as => :student, via: :get

end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Book Room
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %nav.navbar.navbar-inverse
    .container
      .navbar-brand= link_to "BookRoom", root_path

      - if user_signed_in?
        - if current_user.role.eql? "teacher"
          %ul.nav.navbar-nav.navbar-left
            %li= link_to "Book It!", new_schedule_path
            %li= link_to "Settings", edit_user_registration_path
            %li= link_to "Your Schedule", teacher_path(current_user.id)
            %li= link_to "Sign Out", destroy_user_session_path, method: :delete

        - elsif current_user.role.eql? "admin"
          %ul.nav.navbar-nav.navbar-left
            %li= link_to "Settings", edit_user_registration_path
            %li= link_to "User", users_path
            %li= link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          %ul.nav.navbar-nav.navbar-left
            %li= link_to "Settings", edit_user_registration_path
            %li= link_to "Your Schedule", student_path(current_user.id)
            %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-left
          %li= link_to "Join", new_user_registration_path
          %li= link_to "Log In", new_user_session_path

  .container
    -flash.each do |name, msg|
      -if name == "notice"
        =content_tag :div, msg, class: "alert alert-info"
      -else
        =content_tag :div, msg, class: "alert alert-danger"
    =yield